### ISSUE TITLE
Does it work with Ionic 1? 

### ISSUE THREAD

**Issue by xLobito** [snj07/cordova-plugin-root-safety#1]
Greetings.

The question is self-explanatory. I'm working on a project which is based on Ionic 1 and I don't know if this plugin will work on it. 

Appreciate all your replies. Thanks!

**Comment by snj07** [comment]
Yes, it should work with Ionic 1. You may have to downgrade/upgrade google play services if the version in the library is not compatible with your project's google play services version.
