### ISSUE TITLE
plugin Code error while run

### ISSUE THREAD

**Issue by rawcoolpad** [snj07/cordova-plugin-root-safety#2]
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:3: error: package com.google.api.client.json.webtoke
n does not exist
import com.google.api.client.json.webtoken.JsonWebSignature;
                                          ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:4: error: package com.google.api.client.util does no
t exist
import com.google.api.client.util.Key;
                                 ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:24: error: package JsonWebSignature does not exist
public class AttestationResponseModel extends JsonWebSignature.Payload {
                                                              ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:11: error: package com.google.api.client.http does not exist

import com.google.api.client.http.GenericUrl;
                                 ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:12: error: package com.google.api.client.http does not exist

import com.google.api.client.http.HttpRequest;
                                 ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:13: error: package com.google.api.client.http does not exist

import com.google.api.client.http.HttpRequestFactory;
                                 ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:14: error: package com.google.api.client.http does not exist

import com.google.api.client.http.HttpRequestInitializer;
                                 ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:15: error: package com.google.api.client.http does not exist

import com.google.api.client.http.HttpTransport;
                                 ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:16: error: package com.google.api.client.http.javanet does n
ot exist
import com.google.api.client.http.javanet.NetHttpTransport;
                                         ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:17: error: package com.google.api.client.http.json does not
exist
import com.google.api.client.http.json.JsonHttpContent;
                                      ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:18: error: package com.google.api.client.json does not exist

import com.google.api.client.json.JsonFactory;
                                 ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:19: error: package com.google.api.client.json does not exist

import com.google.api.client.json.JsonObjectParser;
                                 ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:20: error: package com.google.api.client.json.jackson2 does
not exist
import com.google.api.client.json.jackson2.JacksonFactory;
                                          ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:21: error: package com.google.api.client.json.webtoken does
not exist
import com.google.api.client.json.webtoken.JsonWebSignature;
                                          ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:22: error: package com.google.api.client.util does not exist

import com.google.api.client.util.Key;
                                 ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:24: error: cannot find symbol
import org.apache.http.conn.ssl.DefaultHostnameVerifier;
                               ^
  symbol:   class DefaultHostnameVerifier
  location: package org.apache.http.conn.ssl
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:29: error: cannot find symbol
    @Key
     ^
  symbol:   class Key
  location: class AttestationResponseModel
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:35: error: cannot find symbol
    @Key
     ^
  symbol:   class Key
  location: class AttestationResponseModel
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:41: error: cannot find symbol
    @Key
     ^
  symbol:   class Key
  location: class AttestationResponseModel

E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:47: error: cannot find symbol
    @Key
     ^
  symbol:   class Key
  location: class AttestationResponseModel
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:53: error: cannot find symbol
    @Key
     ^
  symbol:   class Key
  location: class AttestationResponseModel
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:60: error: cannot find symbol
    @Key
     ^
  symbol:   class Key
  location: class AttestationResponseModel
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:68: error: cannot find symbol
    @Key
     ^
  symbol:   class Key
  location: class AttestationResponseModel
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:75: error: cannot find symbol
    @Key
     ^
  symbol:   class Key
  location: class AttestationResponseModel
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:195: error: cannot find symbol
        @Key
         ^
  symbol:   class Key
  location: class SafetyNetHandler.VerificationRequest
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:207: error: cannot find symbol
        @Key
         ^
  symbol:   class Key
  location: class SafetyNetHandler.VerificationResponse
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:214: error: cannot find symbol
        @Key
         ^
  symbol:   class Key
  location: class SafetyNetHandler.VerificationResponse
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\AttestationResponseModel.java:118: error: method does not override or implement a
method from a supertype
    @Override
    ^
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:52: error: cannot find symbol
            DefaultHostnameVerifier hostnameVerifier = new DefaultHostnameVerifier();
            ^
  symbol:   class DefaultHostnameVerifier
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:52: error: cannot find symbol
            DefaultHostnameVerifier hostnameVerifier = new DefaultHostnameVerifier();
                                                           ^
  symbol:   class DefaultHostnameVerifier
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:63: error: cannot find symbol
            HttpTransport httpTransport = new NetHttpTransport();
            ^
  symbol:   class HttpTransport
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:63: error: cannot find symbol
            HttpTransport httpTransport = new NetHttpTransport();
                                              ^
  symbol:   class NetHttpTransport
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:64: error: cannot find symbol
            JsonFactory jsonFactory = new JacksonFactory();
            ^
  symbol:   class JsonFactory
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:64: error: cannot find symbol
            JsonFactory jsonFactory = new JacksonFactory();
                                          ^
  symbol:   class JacksonFactory
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:67: error: cannot find symbol
            HttpRequestFactory requestFactory = httpTransport.createRequestFactory(new HttpRequestInitializer() {
            ^
  symbol:   class HttpRequestFactory
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:67: error: cannot find symbol
            HttpRequestFactory requestFactory = httpTransport.createRequestFactory(new HttpRequestInitializer() {
                                                                                       ^
  symbol:   class HttpRequestInitializer
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:73: error: cannot find symbol
            GenericUrl url = new GenericUrl(GOOGLE_VERIFICATION_URL + apiKey);
            ^
  symbol:   class GenericUrl
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:73: error: cannot find symbol
            GenericUrl url = new GenericUrl(GOOGLE_VERIFICATION_URL + apiKey);
                                 ^
  symbol:   class GenericUrl
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:75: error: cannot find symbol
            HttpRequest httpRequest = requestFactory.buildPostRequest(url, new JsonHttpContent(jsonFactory, request));
            ^
  symbol:   class HttpRequest
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:75: error: cannot find symbol
            HttpRequest httpRequest = requestFactory.buildPostRequest(url, new JsonHttpContent(jsonFactory, request));
                                                                               ^
  symbol:   class JsonHttpContent
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:130: error: cannot find symbol
        JsonWebSignature jws;
        ^
  symbol:   class JsonWebSignature
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:134: error: cannot find symbol
                jws = JsonWebSignature.parser(JacksonFactory.getDefaultInstance())
                                              ^
  symbol:   variable JacksonFactory
  location: class SafetyNetHandler
E:\raja\test base\rootcheck\platforms\android\app\src\main\java\com\snj07\SafetyNetHandler.java:134: error: cannot find symbol
                jws = JsonWebSignature.parser(JacksonFactory.getDefaultInstance())
                      ^
  symbol:   variable JsonWebSignature
  location: class SafetyNetHandler
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
43 errors
 FAILED

**Comment by snj07** [comment]
@rawcoolpad  Are you using `proguard`?

**Comment by snj07** [comment]
Fix went with v0.0.2. I have added the missing dependencies explicitly which may not be part of the existing Ionic project.
